[2024-06-11T15:48:57.394+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T15:48:57.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-11T15:48:49.697145+00:00 [queued]>
[2024-06-11T15:48:57.428+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-11T15:48:49.697145+00:00 [queued]>
[2024-06-11T15:48:57.428+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T15:48:57.443+0000] {taskinstance.py:2330} INFO - Executing <Task(CustomFileSensor): file_sensor> on 2024-06-11 15:48:49.697145+00:00
[2024-06-11T15:48:57.450+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=489) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T15:48:57.452+0000] {standard_task_runner.py:63} INFO - Started process 491 to run task
[2024-06-11T15:48:57.452+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'file_sensor', 'manual__2024-06-11T15:48:49.697145+00:00', '--job-id', '844', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpcowj60tc']
[2024-06-11T15:48:57.455+0000] {standard_task_runner.py:91} INFO - Job 844: Subtask file_sensor
[2024-06-11T15:48:57.506+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.file_sensor manual__2024-06-11T15:48:49.697145+00:00 [running]> on host e20108ce6780
[2024-06-11T15:48:57.615+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T15:48:49.697145+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T15:48:49.697145+00:00'
[2024-06-11T15:48:57.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T15:48:57.619+0000] {baseoperator.py:399} WARNING - CustomFileSensor.execute cannot be called outside TaskInstance!
[2024-06-11T15:48:57.637+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-06-11T15:48:57.638+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-11T15:49:57.640+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-11T15:50:53.599+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-11T15:50:53.609+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T15:50:53.620+0000] {process_utils.py:132} INFO - Sending 15 to group 491. PIDs of all processes in the group: [491]
[2024-06-11T15:50:53.621+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 491
[2024-06-11T15:50:53.623+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-11T15:50:53.624+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T15:50:53.730+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=491, status='terminated', exitcode=0, started='15:48:56') (491) terminated with exit code 0
