[2024-06-04T17:22:25.583+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T17:22:25.608+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-04T17:22:19.599364+00:00 [queued]>
[2024-06-04T17:22:25.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-04T17:22:19.599364+00:00 [queued]>
[2024-06-04T17:22:25.618+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-04T17:22:25.633+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): file_sensor> on 2024-06-04 17:22:19.599364+00:00
[2024-06-04T17:22:25.644+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T17:22:25.642+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'file_sensor', 'manual__2024-06-04T17:22:19.599364+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpe0uqbjpf']
[2024-06-04T17:22:25.646+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-06-04T17:22:25.646+0000] {standard_task_runner.py:91} INFO - Job 126: Subtask file_sensor
[2024-06-04T17:22:25.720+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.file_sensor manual__2024-06-04T17:22:19.599364+00:00 [running]> on host 9ec08236cafd
[2024-06-04T17:22:25.858+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T17:22:19.599364+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T17:22:19.599364+00:00'
[2024-06-04T17:22:25.861+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T17:22:25.862+0000] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-06-04T17:22:25.874+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-06-04T17:22:25.875+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T17:23:25.875+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T17:24:25.882+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T17:24:36.978+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-04T17:24:36.996+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-04T17:24:37.004+0000] {process_utils.py:132} INFO - Sending 15 to group 68. PIDs of all processes in the group: [68]
[2024-06-04T17:24:37.007+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 68
[2024-06-04T17:24:37.008+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-04T17:24:37.016+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T17:24:37.189+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=68, status='terminated', exitcode=0, started='17:22:25') (68) terminated with exit code 0
