[2024-06-10T11:54:32.328+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T11:54:32.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.task_troup.rm_bash_operator manual__2024-06-10T11:53:05.213127+00:00 [queued]>
[2024-06-10T11:54:32.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.task_troup.rm_bash_operator manual__2024-06-10T11:53:05.213127+00:00 [queued]>
[2024-06-10T11:54:32.414+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-10T11:54:32.441+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task_troup.rm_bash_operator> on 2024-06-10 11:53:05.213127+00:00
[2024-06-10T11:54:32.453+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-10T11:54:32.455+0000] {standard_task_runner.py:63} INFO - Started process 163 to run task
[2024-06-10T11:54:32.455+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'task_troup.rm_bash_operator', 'manual__2024-06-10T11:53:05.213127+00:00', '--job-id', '728', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py.zip/trigger_dag.py', '--cfg-path', '/tmp/tmp4hm4tk9o']
[2024-06-10T11:54:32.460+0000] {standard_task_runner.py:91} INFO - Job 728: Subtask task_troup.rm_bash_operator
[2024-06-10T11:54:32.555+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.task_troup.rm_bash_operator manual__2024-06-10T11:53:05.213127+00:00 [running]> on host 485325dd593b
[2024-06-10T11:54:32.743+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='task_troup.rm_bash_operator' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T11:53:05.213127+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T11:53:05.213127+00:00'
[2024-06-10T11:54:32.747+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T11:54:32.748+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-10T11:54:32.750+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm /opt/***/TRIGGER_FILE/file.txt']
[2024-06-10T11:54:32.767+0000] {subprocess.py:86} INFO - Output:
[2024-06-10T11:54:32.775+0000] {subprocess.py:93} INFO - rm: cannot remove '/opt/***/TRIGGER_FILE/file.txt': No such file or directory
[2024-06-10T11:54:32.776+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-10T11:54:32.779+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T11:54:32.796+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-10T11:54:32.811+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trigger_dag_id, task_id=task_troup.rm_bash_operator, run_id=manual__2024-06-10T11:53:05.213127+00:00, execution_date=20240610T115305, start_date=20240610T115432, end_date=20240610T115432
[2024-06-10T11:54:32.849+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 728 for task task_troup.rm_bash_operator (Bash command failed. The command returned a non-zero exit code 1.; 163)
[2024-06-10T11:54:32.894+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-10T11:54:32.950+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T11:54:32.957+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
