[2024-06-04T17:56:12.292+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T17:56:12.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-04T17:56:05.728867+00:00 [queued]>
[2024-06-04T17:56:12.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-04T17:56:05.728867+00:00 [queued]>
[2024-06-04T17:56:12.348+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-04T17:56:12.376+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): file_sensor> on 2024-06-04 17:56:05.728867+00:00
[2024-06-04T17:56:12.390+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T17:56:12.396+0000] {standard_task_runner.py:63} INFO - Started process 95 to run task
[2024-06-04T17:56:12.391+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'file_sensor', 'manual__2024-06-04T17:56:05.728867+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpby2obfp7']
[2024-06-04T17:56:12.399+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask file_sensor
[2024-06-04T17:56:12.529+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.file_sensor manual__2024-06-04T17:56:05.728867+00:00 [running]> on host 8c874f8dd8e6
[2024-06-04T17:56:12.690+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T17:56:05.728867+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T17:56:05.728867+00:00'
[2024-06-04T17:56:12.699+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T17:56:12.700+0000] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-06-04T17:56:12.725+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-06-04T17:56:12.726+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T17:57:12.682+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T17:58:12.752+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T18:59:03.064+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T19:00:08.686+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T19:36:00.696+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T19:51:38.159+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T22:00:08.855+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T22:24:37.057+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T22:25:37.083+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T22:26:37.087+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T22:27:37.092+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T22:28:37.103+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T22:58:50.109+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T23:03:54.521+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T23:50:13.521+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-04T23:50:13.589+0000] {local_task_job_runner.py:214} ERROR - Heartbeat time limit exceeded!
[2024-06-04T23:50:13.821+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-04T23:50:13.924+0000] {process_utils.py:132} INFO - Sending 15 to group 95. PIDs of all processes in the group: [95]
[2024-06-04T23:50:13.931+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 95
[2024-06-04T23:50:13.935+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-04T23:50:14.008+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T23:50:14.584+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 99, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-04T23:50:14.671+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trigger_dag_id, task_id=file_sensor, run_id=manual__2024-06-04T17:56:05.728867+00:00, execution_date=20240604T175605, start_date=20240604T175612, end_date=20240604T235014
[2024-06-04T23:50:14.902+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=95, status='terminated', exitcode=2, started='17:56:11') (95) terminated with exit code 2
