[2024-06-11T15:51:14.639+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T15:51:14.672+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-11T15:51:02.184015+00:00 [queued]>
[2024-06-11T15:51:14.683+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-11T15:51:02.184015+00:00 [queued]>
[2024-06-11T15:51:14.684+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T15:51:14.702+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): insert_new_row> on 2024-06-11 15:51:02.184015+00:00
[2024-06-11T15:51:14.709+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=543) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T15:51:14.711+0000] {standard_task_runner.py:63} INFO - Started process 545 to run task
[2024-06-11T15:51:14.711+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'insert_new_row', 'manual__2024-06-11T15:51:02.184015+00:00', '--job-id', '852', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmp5stuebf8']
[2024-06-11T15:51:14.714+0000] {standard_task_runner.py:91} INFO - Job 852: Subtask insert_new_row
[2024-06-11T15:51:14.770+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.insert_new_row manual__2024-06-11T15:51:02.184015+00:00 [running]> on host e20108ce6780
[2024-06-11T15:51:14.893+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='insert_new_row' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T15:51:02.184015+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T15:51:02.184015+00:00'
[2024-06-11T15:51:14.895+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T15:51:14.896+0000] {sql.py:276} INFO - Executing: INSERT INTO table_name_1 VALUES(%s, %s, %s);
[2024-06-11T15:51:14.924+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-11T15:51:14.938+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-11T15:51:14.943+0000] {sql.py:470} INFO - Running statement: INSERT INTO table_name_1 VALUES(%s, %s, %s);, parameters: (222, 'default', datetime.datetime(2024, 6, 11, 15, 51, 13, 453825))
[2024-06-11T15:51:14.946+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-11T15:51:14.948+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T15:51:14.961+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=insert_new_row, run_id=manual__2024-06-11T15:51:02.184015+00:00, execution_date=20240611T155102, start_date=20240611T155114, end_date=20240611T155114
[2024-06-11T15:51:15.015+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-11T15:51:15.047+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-11T15:51:15.050+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
