[2024-06-05T07:16:32.035+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T07:16:32.120+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T07:16:23.109531+00:00 [queued]>
[2024-06-05T07:16:32.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T07:16:23.109531+00:00 [queued]>
[2024-06-05T07:16:32.141+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-05T07:16:32.175+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): file_sensor> on 2024-06-05 07:16:23.109531+00:00
[2024-06-05T07:16:32.203+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=537) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T07:16:32.210+0000] {standard_task_runner.py:63} INFO - Started process 549 to run task
[2024-06-05T07:16:32.208+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'file_sensor', 'manual__2024-06-05T07:16:23.109531+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmptsu0lnxf']
[2024-06-05T07:16:32.214+0000] {standard_task_runner.py:91} INFO - Job 185: Subtask file_sensor
[2024-06-05T07:16:32.300+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T07:16:23.109531+00:00 [running]> on host 8c874f8dd8e6
[2024-06-05T07:16:32.470+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T07:16:23.109531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T07:16:23.109531+00:00'
[2024-06-05T07:16:32.473+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T07:16:32.475+0000] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-06-05T07:16:32.494+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-06-05T07:16:32.495+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE
[2024-06-05T07:17:27.726+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-05T07:17:27.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T07:17:27.731+0000] {process_utils.py:132} INFO - Sending 15 to group 549. PIDs of all processes in the group: [549]
[2024-06-05T07:17:27.732+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 549
[2024-06-05T07:17:27.733+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-05T07:17:27.734+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T07:17:27.791+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=549, status='terminated', exitcode=0, started='07:16:32') (549) terminated with exit code 0
